MemberPoint.Web/MemberPoint.Web/Controllers/CardLevelsController.cs
using MemberPoint.Business;
using MemberPoint.Common;
using MemberPoint.Entity.ViewModel;
using MemberPoint.Entity.POCOModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MemberPoint.Web.Controllers
{
    public class CardLevelsController : Controller
    {



        protected CardLevelsService levels = new CardLevelsService();


        /// <summary>
        /// 会员等级列表
        /// </summary>
        /// <returns></returns>
        public ActionResult CardLevelsInfo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CardLevelsInfo(GetPageGetCardLevels getgage)
        {
            var result = levels.GetCardLevelsList(getgage);
            return Json(result.data, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 新增会员卡类别
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            var aa = new CardLevelsViewModel();
            return View(aa);
        }
        [HttpPost]
        public ActionResult Create(CardLevelsViewModel info)
        {
            var result = levels.AddCardLevels(info);
            if (result.resultstatus == ResultStatus.Success)
            {
                return Json(result);
            }
            else
            {
                return Content("添加失败");
            }

        }
        /// <summary>
        /// 修改会员卡类别
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            var result = levels.ShowCardLevels(id);
            return View("Create", result);
        }
        [HttpPost]
        public ActionResult Edit(CardLevelsViewModel info, int id)
        {
            var result = levels.EditCardLevels(info, id);
            if (result.resultstatus == ResultStatus.Success)
            {
                return Json(result);
            }
            else
            {
                return Content("修改失败");
            }

        }
        /// <summary>
        /// 删除会员卡类别
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            var query = levels.DeleteCardLevels(id);
            if (query.resultstatus == ResultStatus.Success)
            {
                return Json(query);
            }
            else
            {
                return Content("删除失败");
            }
        }


    }
}

MemberPoint.Web/MemberPoint.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MemberPoint.Business;
using MemberPoint.Common;
using MemberPoint.Entity.POCOModel;
using MemberPoint.Entity.ViewModel;


namespace MemberPoint.Web.Controllers
{
    public class HomeController : Controller
    {

        private UserService us = new UserService();

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }



        //登陆
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(UsersViewModel uvm)
        {
            var date = us.Login(uvm);
            return Json(date);
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MemberPoint.Web/MemberPoint.Web/Controllers/MemCardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MemberPoint.Business;
using MemberPoint.Common;
using MemberPoint.Entity.POCOModel;
using MemberPoint.Entity.ViewModel;
using MemberPoint.Entity.DTOModel;
using System.Data;

namespace MemberPoint.Web.Controllers
{
    public class MemCardsController : Controller
    {

        private  MemCardsService member = new MemCardsService();
        private ExchangeGiftsService exchange = new ExchangeGiftsService();
        // GET: MemCards

        #region 查找会员
        public ActionResult FindMenberCard()
        {
            return View();
        }
        /// <summary>
        /// 查找会员
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult FindMenberCard(GetPageMemCardsViewModel getMember)
        {
            var list = member.FindMemCards(getMember);
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 积分兑换礼品
        //操作礼品表(ExchangGifts)
        public ActionResult PointChangeGifts()
        {
            return View();

        }
        [HttpPost]
        public ActionResult PointChangeGifts(GetPageMemCardsViewModel getMember)
        {
            var list = exchange.PointChangeGifts(getMember);
            return Json(list.data, JsonRequestBehavior.AllowGet);
        }

        #endregion


        private MemCardsService memcards = new MemCardsService();
        #region 会员展示
        /// <summary>
        /// 展示会员信息
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 获取用户数据
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult GetMemCardsList(GetPageViewModel model)
        {
            OpearteResult result;
            //获取当前用户所在店铺
            BaseService<MemberPoint.Entity.POCOModel.Users> UserBase = new BaseService<Entity.POCOModel.Users>();
            var user = User as MyFormsPrincipal<loginUserDataDtoModel>;
            result = memcards.GetMemCardsList(model, UserBase.Find(u => u.U_ID == user.UserData.U_ID).S_ID);
            return Json(result.data, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region 添加会员信息
        /// <summary>
        /// 添加会员
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            MemCardsViewModel m = new MemCardsViewModel();
            return View(m);
        }
        [HttpPost]
        public ActionResult Create(MemCardsViewModel modelinfo)
        {
            try
            {
                OpearteResult reselt;
                reselt = memcards.AddInfo(modelinfo);

                return Json(reselt);
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
        /// <summary>
        /// 查询姓名是否存在
        /// </summary>
        /// <param name="mName"></param>
        /// <returns></returns>
        public ActionResult selName(string mName)
        {
            OpearteResult result;
            if (memcards.Find(m => m.MC_Name == mName) != null)
            {
                result = new OpearteResult(ResultStatus.Success, "推荐人存在");
            }
            else
            {
                result = new OpearteResult(ResultStatus.Error, "推荐人不存在");
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        #endregion


        #region 修改会员信息
        /// <summary>
        /// 修改会员信息
        /// </summary>
        /// <returns></returns>
        public ActionResult Edit(string id)
        {

            try
            {
                OpearteResult result = memcards.Getfirst(id);

                return View("Create", result.data);
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }
        [HttpPost]
        public ActionResult Edit(MemCardsViewModel model)
        {
            try
            {
                OpearteResult reselt;
                reselt = memcards.UpdateMemCards(model);
                return Json(reselt);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        #endregion

        #region 删除会员信息
        /// <summary>
        /// 删除
        /// </summary>
        /// <returns></returns>
        public ActionResult Delete(string id)
        {
            OpearteResult result = memcards.DeleteMemCards(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 挂失锁定
        /// <summary>
        /// 挂失/锁定
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Lock(string id)
        {
            MemCardsViewModel m = new MemCardsViewModel()
            {
                MC_CardID = id
            };
            return View(m);
        }
        [HttpPost]
        public ActionResult Lock(MemCardsViewModel model)
        {
            try
            {
                OpearteResult result = memcards.LockMemCards(model);
                return Json(result);
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
        #endregion

        #region 会员转账
        public ActionResult VIPTransfer(string id)
        {
            var mem = memcards.Getfirst(id).data as MemCardsViewModel;
            TransferViewModel transfer = new TransferViewModel
            {
                Out_MC_CardID = mem.MC_CardID,
                Out_MC_Name = mem.MC_Name,
                Out_MC_Point = mem.MC_Point,
                Out_MC_TotalMoney = mem.MC_TotalMoney,
                MC_Money = mem.MC_Money
            };
            return View(transfer);
        }
        /// <summary>
        /// 执行转账
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult VIPTransfer(TransferViewModel model)
        {
            OpearteResult result;
            if (ModelState.IsValid)
            {
                var users = User as MyFormsPrincipal<loginUserDataDtoModel>;
                model.UserId = users.UserData.U_ID;
                result = memcards.VipTransfer(model);

            }
            else
            {
                result = new OpearteResult(ResultStatus.Error, "不能为空");
            }
            return Json(result);
        }

        /// <summary>
        /// 根据当前用户输入的卡号查询
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult VIPInto(string id)
        {
            OpearteResult result = memcards.Getfirst(id);
            return Json(result, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region 会员换卡
        /// <summary>
        /// VIP换卡
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult VIPReset(string id)
        {
            OpearteResult result = memcards.ResetGetBycard(id);
            return View(result.data);
        }


        /// <summary>
        /// 换卡事件
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult VIPReset(MemCardsViewModel model)
        {
            OpearteResult result = memcards.UpdateCards(model);
            return Json(result);
        }
        #endregion

        #region 导出Excel

        /// <summary>
        /// 导出Excel
        /// </summary>
        /// <returns></returns>
        public ActionResult ExportExcelNew()
        {
            string json = Request.Params["data"];
            try
            {
                DataTable dt = ExcelHelper.JsonToDataTable(json);
                string pathDestop = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
                ExcelHelper.GridToExcelByNPOI(dt, pathDestop + "\\" + "会员列表-" + DateTime.Now.ToString("yyyy-MM-dd") + "导出" + ".xls");
                return Content("1");
            }
            catch (Exception)
            {
                return Content("-1");
            }
        }
        #endregion


    }
}

MemberPoint.Web/MemberPoint.Web/Controllers/ShopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MemberPoint.Business;
using MemberPoint.Entity.POCOModel;
using MemberPoint.Entity.ViewModel;
using MemberPoint.Common;


namespace MemberPoint.Web.Controllers
{
    public class ShopsController : Controller
    {
        // GET: Shops

        private ShopsService ss = new ShopsService();
        /// <summary>
        ///  展示店铺信息
        /// </summary>
        /// <returns></returns>


        public ActionResult ShowShopInfo()
        {
            return View();
        }

        [HttpPost]

        public ActionResult ShowShopInfo(int page, int rows, string Sname, string SContactName, string adress)
        {
            var date = ss.GetInfo(page, rows, Sname, SContactName, adress);
            return Json(date.data);
        }
        public ActionResult BindShopsType()
        {
            //var list = db.GoodsType.Select(a => new SelectListItem { Text = a.CName, Value = a.Cid.ToString() });
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (int i in Enum.GetValues(typeof(EnumTypes.ShopTypeEnum)))
            {
                SelectListItem listitem = new SelectListItem() { Text = Enum.GetName(typeof(EnumTypes.ShopTypeEnum), i), Value = i.ToString() };
                list.Add(listitem);
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 添加店铺
        /// </summary>
        /// <returns></returns>
        public ActionResult AddShops()
        {
            //ViewBag.type=BindShopsType();
            return View();
        }

        [HttpPost]
        public ActionResult AddShops(ShopsViewModel uvm)
        {

            //SelectListItem listitem = new SelectListItem();
            //uvm.S_Category =Convert.ToInt32(listitem.Value);
            //ViewBag.type = BindShopsType();
            var a = ss.AddShops(uvm);
            return Json(a);
        }
        /// <summary>
        /// 删除店铺
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        //[HttpPost]
        public ActionResult DeleteInfo(int Id)
        {

            var a = ss.DeleteInfo(Id);
            return Json(a);

        }
        /// <summary>
        /// 修改店铺信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult EditShop(int id)
        {
            var a = ss.GetShopsById(id);
            return View("AddShops", a.data);
        }

        [HttpPost]
        public ActionResult EditShop(ShopsViewModel uvm, int id)
        {
            var result = ss.EditShop(uvm, id);
            return Json(result);
        }
        /// <summary>
        /// 分配店长账号
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Assigned(int id)
        {
            UsersViewModel mo = new UsersViewModel();
            mo.S_ID = id;
            return View(mo);
        }
        [HttpPost]
        public ActionResult Assigned(UsersViewModel mo)
        {

            UserService us = new UserService();
            var a = us.AddShopManager(mo);
            return Json(a);

        }


    }
}

MemberPoint.Web/MemberPoint.Web/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MemberPoint.Business;
using MemberPoint.Common;
using MemberPoint.Entity.POCOModel;
using MemberPoint.Entity.ViewModel;

namespace MemberPoint.Web.Controllers
{
    public class UsersController : Controller
    {

        private UserService us = new UserService();


        /// <summary>
        /// 下拉框
        /// </summary>
        /// <param name="shops"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UsersList()
        {
            ShopsService ss = new ShopsService();
            var date = ss.ShopsList();
            return Json(date.data);
        }

        /// <summary>
        ///  展示用户信息
        /// </summary>
        /// <returns></returns>
        public ActionResult ShowUsersInfo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ShowUsersInfo(int page, int rows,string sid,string uname)
        {
            var date = us.GetInfo(page,rows,sid,uname);
            return Json(date.data);
        }
        
        public ActionResult AddUsersInfo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddUsersInfo(UsersViewModel uvm)
        {
            var a = us.AddUser(uvm);
            return Json(a);
        }

        public ActionResult UpdateUsersInfo(int id)
        {
            var a = us.GetUsersById(id);
            return View(a.data);
        }

        [HttpPost]
        public ActionResult UpdateUsersInfo(UsersViewModel uvm,int id)
        {
            var result = us.EditUser(uvm,id);
            return Json(result);
        }


        [HttpPost]
        public ActionResult DeleteInfo(int id)
        {
            var a = us.DeleteInfo(id);
            return Json(a);

        }



    }
}

MemberPoint.Web/MemberPoint.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MemberPoint.Web/MemberPoint.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MemberPoint.Web/MemberPoint.Web/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    var users = User as MemberPoint.Entity.DTOModel.MyFormsPrincipal<MemberPoint.Entity.DTOModel.loginUserDataDtoModel>;
}

<!DOCTYPE html>


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>主页</title>




    <style type="text/css">
        a {
            text-decoration: none;
            color: black;
        }


        #nav ul li {
            border: 0px solid red;
            margin-top: 10px;
            position: relative;
            right: 30px;
        }
    </style>

</head>
<body class="easyui-layout">
    <form id="form1">


        @*头部*@
        <div data-options="region:'north',collapsible:false, split:false" style="height: 60px;  text-align:center;color:white;background:url(/fonts/logo1.png)no-repeat;">
            <h3 style="font-size:16px; color:black;">会员消费积分管理平台</h3>
         
            @if (users != null)
            {
            <span style="border:0px solid red; width:200px; height:20px;display:block; position:absolute;left:950px; bottom:15px; color:black;"> 欢迎你的登录:@users.UserData.U_LoginName</span>
            }
            else
            {
            <span style="border:0px solid red; width:200px; height:20px;display:block; position:absolute;left:950px; bottom:15px; color:black;">尚未登录</span>
            }
           


        </div>

        @*导航栏*@
        <div data-options="region:'west',title:'菜单导航',split:false,collapsible:false" style="width: 200px; background: #EFF2F9;">
            <div id="nav" class="easyui-accordion" style="width: 198px;">
                <div title="用户管理" data-options="iconCls:'icon-reload'" style="padding: 10px;">
                    <ul>
                        <li class="easyui-tree" data-link='@Url.Action("ShowUsersInfo","Users")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">用户列表</a></li>
                    </ul>
                </div>
                <div title="礼品管理" data-options="iconCls:'icon-print'" style="padding: 10px;">
                    <ul>
                        <li class="easyui-tree" data-link='@Url.Action("Index","ExchangGifts")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">礼品列表</a></li>
                    </ul>
                </div>
                <div title="会员管理" data-options="iconCls:'icon-print'" style="padding: 10px;">
                    <ul>
                        <li class="easyui-tree" data-link='@Url.Action("Index","MemCards")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">会员列表</a></li>
                    </ul>
                </div>

                <div title="会员消费" data-options="iconCls:'icon-cut'" style="padding: 10px;">
                    <ul>
                        <li class="easyui-tree"  data-link='@Url.Action("FindMenberCard","MemCards")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">快速消费</a></li>
                        <li class="easyui-tree"  data-link='@Url.Action("DeductMemberPoint","ConsumeOrder")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">会员减积分</a></li>
                        <li class="easyui-tree"  data-link='@Url.Action("ConsumeOrdersList","ConsumeOrder")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">消费历史记录</a></li>
                    </ul>
                </div>

                <div title="积分兑换" data-options="iconCls:'icon-cut'" style="padding: 10px;">
                    <ul>
                        <li class="easyui-tree"  data-link='@Url.Action("PointChangeGifts","MemCards")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">积分兑换礼品</a></li>
                        <li class="easyui-tree"  data-link='@Url.Action("GoTORecash","ConsumeOrder")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">积分返现</a></li>
                        <li class="easyui-tree"  data-link='@Url.Action("ExchangLogsList","ExchangLogs")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">兑换历史记录</a></li>
                    </ul>
                </div>

                <div title="统计中心" data-options="iconCls:'icon-reload'" style="padding: 10px;">
                    <ul>
                        <li class="easyui-tree"  data-link='@Url.Action("ConsumeOrderInfo","ConsumeOrder")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">快速消费统计</a></li>
                        <li class="easyui-tree"  data-link='@Url.Action("ConsumeOrdersListAll","ConsumeOrder")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">会员消费情况统计</a></li>
                        <li class="easyui-tree"  data-link='@Url.Action("ShowConsumeOrderInfo","ConsumeOrder")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">减积分统计</a></li>
                        <li class="easyui-tree"  data-link='@Url.Action("ConsumeOrderInfo","ConsumeOrder")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">积分返现统计</a></li>
                        <li class="easyui-tree"  data-link='@Url.Action("ExchangLogsHistoryList","ExchangLogs")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">礼品兑换统计</a></li>
                         </ul>
                </div>
                <div title="系统管理" data-options="iconCls:'icon-back'" style="padding: 10px;">
                    <ul>
                        <li class="easyui-tree" data-link='@Url.Action("ShowShopInfo","Shops")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">店铺管理</a></li>
                        <li class="easyui-tree"  data-link='@Url.Action("CardLevelsInfo","CardLevels")'><span class="icon-group" style="height:16px;width:16px;display:inline-block"></span><a href="javascript:void(0)">会员等级管理</a></li>
                    </ul>
                </div>
            </div>

        </div>



        @*右侧内容*@
        <div data-options="region:'center'," style="padding: 5px;background: #EFF2F9;">
            <div id="tttt" class="easyui-tabs" style="width: 100%; height: 100%; background:url(/fonts/backimg1.png)no-repeat; ">
                @*<div title="主页" data-options="closable:false" style="padding: 20px; display: none;background: #EFF2F9;">
                    

                </div>*@
             
            </div>
        </div>


        @*底部*@
        <div data-options="region:'south',collapsible:false,split:false" style="height: 50px; background: #EFF2F9; text-align: center; line-height: 40px;">
            <strong>版权所有@Copyright&copy;2015&reg;&nbsp; 会员消费积分管理平台</strong>
        </div>


    </form>

    <script type="text/javascript">

        $(function () {


              @*$('#tttt').dialog({
                  method:"get",
                  // href: '@Url.Action("Create","Admin")',
                  href: '@Url.Action("Login", "Home")',
                  width: 500,
                  height: 350,
                  closed: false,
                  cache: false,
                  modal: true,
                  draggable: false,
                  title: '添加角色'
              });*@


            $("#nav div ul li").click(function () {
                if ($("#tttt").tabs("exists", $(this).text())) {
                    $("#tttt").tabs("select", $(this).text());
                }
                else {
                    var content = "<iframe src=" + $(this).attr('data-link') + " scrolling='no' frameborder='0' style='margin-left:-10px; margin-top:-5px; border:0px'  width='100%;' height='100%;'></iframe>";
                    var icon=$(this).attr("data-options");
                    $('#tttt').tabs('add', {
                        title: $(this).html(),
                        selected: true,
                        closable: true,
                        iconCls: icon,
                        content: content
                       // href: $(this).attr('data-link')
                    });

                }

            });

        })


    </script>
</body>
</html>

MemberPoint.Web/MemberPoint.Web/Views/Home/Login.cshtml
@model MemberPoint.Entity.ViewModel.UsersViewModel

@{
    ViewBag.Title = "Login";
}

<style type="text/css">
    #btnsubmit{
        font-size:16px;
    }

</style>
<script type="text/javascript">
    $(function () {

        $("#btnsubmit").click(function () {
            $("#myform").form("submit", {
                onSubmit: function () {
                    var IsValid = $(this).form('validate');
                    return IsValid;
                },
                success: function (msg) {
                    var json = JSON.parse(msg);
                    if (json.resultstatus == 1) {
                        location.href = '@Url.Action("Index","Home")';
                    }
                    else {
                        $.messager.alert("提示信息", json.Msg, "error");
                    }

                }
            })

        });

    })

</script>

<body style="margin:0; padding:0;background-image:url(/fonts/tats.jpg);background-repeat:no-repeat">
    <form id="myform" method="post" class="easyui-form" data-options="novalidate:true">
        <div style="margin-top:-10px; width:300px; height:300px; margin-left:535px; ">

        </div>
        <div style="background-color:white; width:320px; height:220px; margin-left:520px; margin-top:-75px;">
            <table align="center" ; width="200" height="220" border="0" style="text-align:center;">
                <tr>
                    <td>用户名</td>
                    <td>
                        @Html.EditorFor(model => model.U_LoginName, new { htmlAttributes = new { @class = "easyui-textbox", @data_options = "required:true" } })
                    </td>
                </tr>
                <tr>
                    <td>密&nbsp;&nbsp;&nbsp;码</td>
                    <td>
                        @Html.EditorFor(model => model.U_Password, new { htmlAttributes = new { @class = "easyui-textbox", @data_options = "required:true" } })
                    </td>
                </tr>
                <tr >
                    <td colspan="2" style="text-align:center;">
                        <a href="Javascript:void(0)" id="btnsubmit" class="easyui-linkbutton" style="width:253px; height:35px; line-height:35px;font-size:18px;">登录</a>
                    </td>
                </tr>

            </table>

        </div>

        <div style="border:0px solid red;background-image:url(/fonts/ser1.png); width:1364px; height:80px; margin-top:147px;">

        </div>
    </form>
</body>