MemberPoint.Web/MemberPoint.Web/Controllers/ExchangLogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MemberPoint.Business;
using MemberPoint.Common;
using MemberPoint.Entity.POCOModel;
using MemberPoint.Entity.ViewModel;
using MemberPoint.Entity.DTOModel;

namespace MemberPoint.Web.Controllers
{
    public class ExchangLogsController : Controller
    {
        private ExchangLogsService exchange = new ExchangLogsService();
        

        // GET: ExchangLogs
        #region 兑换历史记录
        public ActionResult ExchangLogsHistoryList()
        {

            return View();
        }

        [HttpPost]
        public ActionResult ExchangLogsHistoryList(GetPageExchangLogsViewModel change)
        {
            var changes = exchange.GetExchangLogsInfo(change);
            return Json(changes.data, JsonRequestBehavior.AllowGet);
        }



        #endregion

        #region 礼品兑换统计
        public ActionResult ExchangLogsList()
        {

            return View();
        }

        [HttpPost]
        public ActionResult ExchangLogsList(GetPageExchangLogsViewModel change)
        {
            var changes = exchange.GetExchangLogsInfo(change);
            return Json(changes.data, JsonRequestBehavior.AllowGet);
        }
        #endregion


        #region 马上兑换
        /// <summary>
        /// 马上兑换
        /// </summary>
        /// <param name="shuju"></param>
        /// <returns></returns>
    

        public ActionResult ComeConversion(/*string id,string MC_CardID*/)
        {
            //return Content(id,MC_CardID);
           var id= Request.QueryString["str"];
            var MC_CardID = Request.QueryString["mc_id"];
            var user = User as MyFormsPrincipal<loginUserDataDtoModel>;
            var userid = user.UserData.U_ID;
            var date = exchange.ComeConversion(id,MC_CardID, userid);

            if (date.resultstatus == ResultStatus.Success)
            {
                return RedirectToAction("PointChangeGifts", "MemCards");
            }
            else
            {
                return View();
            }


        }


        #endregion







    }
}

MemberPoint.Web/MemberPoint.Web/Views/ExchangLogs/ExchangLogsHistoryList.cshtml
@{
    ViewBag.Title = "ExchangLogsHistoryList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<fieldset style="border:1px solid #A4D1F0; height:60px; width:1000px;background:#fafafa;">
    <legend style="font-size:18px;">查找会员</legend>
    <div data-options="region:'center'" style="margin:8px;">
        <div id="tb">
            卡号/手机:<input id="MC_CardID" type="text" class="easyui-textbox" style="width:120px"></input>
            <a id="search" href="javascript:void(0)" class="easyui-linkbutton" style="width:100px">全部兑换记录</a>
        </div>
</fieldset>
<div id="new" style="display:none;background:#fafafa;">
    <iframe frameborder="no" border="0" marginwidth="0" marginheight="0" id="frml" scrolling="no" width="100%" height="100%"></iframe>
</div><br />
<table id="dg" style="width:1030px;"></table>
    </div>

<script type="text/javascript">
    //展示信息
    $(function () {
        $('#dg').datagrid({
            url: '@Url.Action("ExchangLogsList", "ExchangLogs")',
            method: 'post',
            singleSelect: true,
            pagination: true,
            pageSize: 10,
            pageList: [10],
            columns: [[
            { field: 'EG_GiftName', title: '礼品名称', width: 100 },
             { field: 'EL_Number', title: '兑换数量', width: 100 },
            { field: 'EL_Point', title: '所用积分', width: 100 },
            {
                field: 'EL_CreateTime', title: '兑换时间', width: 150,
                formatter: function (data) { return FormatJsonTime(data) }
            },

            ]],
            rownumbers: true
        });

        $("#search").click(function () {
            $('#dg').datagrid("load", {
              
                MC_CardID: $("#MC_CardID").val()
            })
        })
    })
</script>

MemberPoint.Web/MemberPoint.Web/Views/ExchangLogs/ExchangLogsList.cshtml
@{
    ViewBag.Title = "ExchangLogsList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<fieldset style="border:1px solid #A4D1F0; height:60px; width:1000px;background:#fafafa;">
    <legend style="font-size:18px;">查询</legend>
    <div data-options="region:'center'" style=" margin:8px">
        <div id="tb">
            卡号/手机:<input id="MC_CardID" type="text" class="easyui-textbox" style="width:120px"></input>
            兑换日期：<input id="startTime" type="text" class="easyui-datebox" style="width:120px"></input>
            至：<input id="endTime" type="text" class="easyui-datebox" style="width:120px"></input>
            <a id="search" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-search'" style="width:70px">搜索</a>
        </div>
</fieldset>
<div id="new" style="display:none;background:#fafafa;">
    <iframe frameborder="no" border="0" marginwidth="0" marginheight="0" id="frml" scrolling="no" width="100%" height="100%"></iframe>
</div><br />
<table id="dg" style="width:1030px;"></table>
    </div>

<script type="text/javascript">
    //展示信息
    $(function () {
        $('#dg').datagrid({
            url: '@Url.Action("ExchangLogsList", "ExchangLogs")',
            method: 'post',
            singleSelect: true,
            pagination: true,
            pageSize: 10,
            pageList: [10],
            columns: [[
            //{ field: 'EL_ID', title: '兑换记录编号', width: 100 },
            //{ field: 'S_ID', title: '店铺编号', width: 100 },
            //{ field: 'U_ID', title: '用户编号', width: 100 },
            //{ field: 'MC_ID', title: '会员编号', width: 100 },
            { field: 'MC_CardID', title: '会员卡号', width: 100 },
             { field: 'MC_Name', title: '会员姓名', width: 100 },
            { field: 'EG_ID', title: '礼品编号', width: 100 },
            //{ field: 'EG_GiftCode', title: '礼品编码', width: 100 },
            { field: 'EG_GiftName', title: '礼品名称', width: 100 },
             { field: 'EL_Number', title: '兑换数量', width: 100 },
            { field: 'EL_Point', title: '所用积分', width: 100 },
            {
                field: 'EL_CreateTime', title: '兑换时间', width: 150,
                formatter: function (data) { return FormatJsonTime(data) }
            },

            ]],
            rownumbers: true
        });

        $("#search").click(function () {
            $('#dg').datagrid("load", {
                startTime: $("#startTime").val(),
                endTime: $("#endTime").val(),
                MC_CardID: $("#MC_CardID").val()
            })
        })
    })
</script>