MemberPoint.Web/MemberPoint.Web/Controllers/ExchangGiftsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MemberPoint.Business;
using MemberPoint.Common;
using MemberPoint.Entity.POCOModel;
using MemberPoint.Entity.ViewModel;

namespace MemberPoint.Web.Controllers
{
    public class ExchangGiftsController : Controller
    {
        private ExchangeGiftsService exchangGifts = new ExchangeGiftsService();

        // GET: ExchangGifts
        #region  修改兑换数量
        /// <summary>
        /// 修改兑换数量
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult EG_ExchangNumEdit(int id)
        {
            var change = exchangGifts.GetExchangGiftsEG_ID(id);
            return View(change.data);
        }
        [HttpPost]
        public ActionResult EG_ExchangNumEdit(ExchangGiftsViewModel getGifts)
        {
            var list = exchangGifts.EditEG_ExchangNum(getGifts);
            return Json(list, JsonRequestBehavior.AllowGet);

        }




        #endregion

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        // GET: ExchangGifts
        /// <summary>
        /// 礼品列表
        /// </summary>
        /// <returns></returns>

        public ActionResult Index(PageFenYe pageDate)
        {
            OpearteResult result = exchangGifts.GetExchangGifts(pageDate);
            return Json(result.data);
        }
        public ActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// 添加礼品
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]

        public ActionResult Create(ExchangGiftsViewModel exchang)
        {
            OpearteResult result;
            try
            {
                result = exchangGifts.AddExchang(exchang);
                if (result.resultstatus == ResultStatus.Success)
                {
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(result);
                }

            }
            catch
            {
                return View();
            }
        }
        /// <summary>
        /// 编辑
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            //调用userService的方法
            OpearteResult result = exchangGifts.GetExchangFirst(id);
            return View("Create", result.data);
        }
        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="exchang"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(ExchangGiftsViewModel exchang, int id)
        {
            OpearteResult result;
            try
            {
                result = exchangGifts.UpdateExchang(exchang, id);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            //调用userService的方法
            OpearteResult result = exchangGifts.DeleteExchang(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


    }
}

MemberPoint.Web/MemberPoint.Web/Views/ExchangGifts/Create.cshtml
@model MemberPoint.Entity.ViewModel.ExchangGiftsViewModel

@{
    ViewBag.Title = "Create";
}

<script type="text/javascript">
    $(function () {
        $("#close1").click(function () {
            window.parent.$("#win").window("close");
        })

        $("#submit1").click(function () {
            var pathurl;
            if ($("#EG_ID").val() != "" && parseInt($("#EG_ID").val()) > 0)
            {
                pathurl = "@Url.Action("Edit", "ExchangGifts")";

            }
            else
            {

                pathurl="@Url.Action("Create", "ExchangGifts")";
            }
            $("#form_Supplier").form("submit", {
                url: pathurl,
                onSubmit:function(){
                    var isvalidate = $(this).form("enableValidation").form("validate");
                    return isvalidate;
                },
                success:function(data)
                {
                   var json= JSON.parse(data);
                   if (json.resultstatus == 1)
                   {
                       window.parent.$.messager.alert("提示", json.Msg, "info");
                       //$.messager.alert("提示信息", json.Msg, "success");
                       //关闭弹窗
                       window.parent.$("#win").window("close");
                       //刷新列表
                       window.parent.$("#dg").datagrid("reload");
                   }
                   else
                   {
                       $.messager.alert("温馨提示", json.Msg, "error");
                   }
                }

            })
        })


    })

</script>

@using (Html.BeginForm("", "", FormMethod.Post, new { id = "form_Supplier" }))
{
    <fieldset>
        <legend>添加/修改</legend>
        <table>

            <tr>
                <td>@Html.LabelFor(model => model.S_ID)</td>
                <td>@Html.EditorFor(model => model.S_ID, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true", missingMessage = "礼品编码" } })</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.EG_GiftCode)</td>
                <td>@Html.EditorFor(model => model.EG_GiftCode, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true", missingMessage = "礼品编码" } })</td>
            </tr>

            <tr>
                <td>@Html.LabelFor(model => model.EG_GiftName)</td>
                <td>@Html.EditorFor(model => model.EG_GiftName, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true", missingMessage = "礼品名称" } })</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.EG_Photo)</td>
                <td>@Html.EditorFor(model => model.EG_Photo, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true", missingMessage = "礼品图片" } })</td>
            </tr>

            <tr>
                <td>@Html.LabelFor(model => model.EG_Point)</td>
                <td>@Html.EditorFor(model => model.EG_Point, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true", missingMessage = "所需积分" } })</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.EG_Number)</td>
                <td>@Html.EditorFor(model => model.EG_Number, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true", missingMessage = "总数量" } })</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.EG_ExchangNum)</td>
                <td>@Html.EditorFor(model => model.EG_ExchangNum, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true", missingMessage = "已兑换的数量" } })</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.EG_Remark)</td>
                <td>@Html.EditorFor(model => model.EG_Remark, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true", missingMessage = "备注" } })</td>
            </tr>

            <tr>
                <td>@Html.HiddenFor(model => model.EG_ID)</td>
                <td>
                    <a href="javascript:void(0)" id="submit1" class="easyui-linkbutton" data-options="iconCls:'icon-ok'">提交</a>
                    <a href="javascript:void(0)" id="close1" class="easyui-linkbutton" data-options="iconCls:'icon-cancel'">关闭</a>
                </td>
            </tr>

        </table>
    </fieldset>

}

MemberPoint.Web/MemberPoint.Web/Views/ExchangGifts/EG_ExchangNumEdit.cshtml
@model MemberPoint.Entity.ViewModel.ExchangGiftsViewModel

@{
    ViewBag.Title = "EG_ExchangNumEdit";
}

@using (Html.BeginForm("", "", FormMethod.Post, new { id = "ff" }))
{
    @Html.AntiForgeryToken()


    <table table class="aa" style="margin:0 auto; margin-top:40px;">

        <tr>
            <td>
                @Html.LabelFor(model => model.EG_ExchangNum)
            </td>
            <td>
                @Html.EditorFor(model => model.EG_ExchangNum, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true" } })
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <a id="btnAdd" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-ok'" style="width:60px">提交</a>
                <a id="btnNull" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-cancel'" style="width:60px" onclick="formclear()">重置</a>
            </td>
        </tr>

    </table>
    @Html.HiddenFor(model => model.EG_ID)
}
<script type="text/javascript">
    $(function () {
        $("#btnAdd").click(function () {
            $("#ff").form("submit", {
                url:'@Url.Action("EG_ExchangNumEdit", "ExchangGifts")',
                onSubmit: function () {
                    var isValid = $(this).form("validate");
                    return isValid;
                },
                success: function (result) {
                    var json = JSON.parse(result);
                    if (json.resultstatus == 1) {
                        window.parent.$('#new').dialog("close");
                        window.parent.$.messager.alert("温馨提示", json.Msg, 'info');
                        window.parent.$('#dg').datagrid("reload");
                        }
                    else {
                        $.messager.alert('我的消息', "修改失败", 'info');
                    }
                }

            })

        })
    })




</script>

MemberPoint.Web/MemberPoint.Web/Views/ExchangGifts/Index.cshtml
@model IEnumerable<MemberPoint.Entity.ViewModel.ExchangGiftsViewModel>

@{
    ViewBag.Title = "Index";
}



<script type="text/javascript">
    $(function () {
        //绑定下拉框
        $("#dg").datagrid({
            url: "@Url.Action("Index", "ExchangGifts")",
            method: "post",
            pagination: true,
            pageSize: 5,
            pageList: [5, 10, 15],
            columns: [[
                    { field: 'EG_ID', title: '礼品编号', width: 100, align: 'center' },
                      { field: 'S_ID', title: '店铺编号', width: 100, align: 'center' },
                        { field: 'EG_GiftCode', title: '礼品编码', width: 100, align: 'center' },
                          { field: 'EG_GiftName', title: '礼品名称', width: 100, align: 'center' },
                            { field: 'EG_Photo', title: '礼品图片', width: 100, align: 'center' },
                            { field: 'EG_Point', title: '所需积分', width: 100, align: 'center' },
                             { field: 'EG_Number', title: '总数量', width: 100, align: 'center' },
                              { field: 'EG_ExchangNum', title: '已兑换数量', width: 100, align: 'center' },
                               { field: 'EG_Remark', title: '备注', width: 100, align: 'center' }
            ]]
        })

        //添加
        $("#btnadd").click(function () {
            $("#win").window({title: "添加礼品", modal: true }).window("open");
            $("#ifraadd").attr("src", "@Url.Action("Create", "ExchangGifts")");
        })
        //修改
        $("#btnalter").click(function () {
            var row = $("#dg").datagrid("getSelected");
            if(row)
            {
                $("#win").window({title: "修改礼品", modal: true }).window("open");
                $("#ifraadd").attr("src", "@Url.Action("Edit/", "ExchangGifts")" + row.EG_ID);


            }
            else
            {
                $.messager.alert("温馨提示", "请选择要修改的行", "error");
            }

        })
        //删除
        $("#btnremove").click(function () {
            var row = $("#dg").datagrid("getSelected");
            if(row)
            {

                $.messager.confirm("操作提示", "确定要删除吗", function (r) {
                    if(r)
                    {
                        $.post("@Url.Action("Delete", "ExchangGifts")", { id: row.EG_ID }, function (data) {
                            if (data.resultstatus == 1)
                            {
                                $.messager.alert("温馨提示", data.Msg, "info");
                                $("#dg").datagrid("reload");
                            }
                            else
                            {
                                //$.messager.alert("温馨提示", data.Msg, "error");
                            }
                        },"json")
                    }
                })
            }
            else
            {
                $.messager.alert("温馨提示", "请选择要删除的行", "error");
            }

        })

    })
</script>

<body>
    <div id="cc" class="easyui-layout" style="width:200px;height:400px;" data-options="fit:true">
        <div data-options="region:'center'" style="padding:10px;background:#eee;">

            <a id="btnadd" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-add'" style="background:#eee;">新增</a>
            <a id="btnalter" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-edit'" style="background:#eee;">修改</a>
            <a id="btnremove" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-remove'" style="background:#eee;">删除</a>
         

            <table id="dg" class="easyui-datagrid" style="width:1000px;height:90%;text-align:center;background:#eee; overflow:auto"
                   data-options="fitColumns:true,singleSelect:true ,method: 'get',rownumbers:true"></table>
        </div>
    </div>

    <div id="win" data-options="iconCls:'icon-add'" style="width:440px;height:430px">
        <iframe id="ifraadd" frameborder="0" scrolling="no" style="width:100%;height:100%"></iframe>
    </div>
</body>