MemberPoint.Web/MemberPoint.Web/Controllers/ConsumeOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MemberPoint.Business;
using MemberPoint.Common;
using MemberPoint.Entity.POCOModel;
using MemberPoint.Entity.ViewModel;
using MemberPoint.Entity.DTOModel;

namespace MemberPoint.Web.Controllers
{
    public class ConsumeOrderController : Controller
    {
        private ConsumeOrdersService consume = new ConsumeOrdersService();
        // GET: ConsumeOrder

        #region 消费历史记录
        public ActionResult ConsumeOrdersList()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ConsumeOrdersList(GetPageConsumeOrdersViewModel consumeorder)
        {
            var list = consume.GetConsumeOrdersList(consumeorder);
            return Json(list.data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 消费历史记录统计
        public ActionResult ConsumeOrdersListAll()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ConsumeOrdersListAll(GetPageConsumeOrdersViewModel consumeorder)
        {
            var list = consume.GetConsumeOrdersList(consumeorder);
            return Json(list.data, JsonRequestBehavior.AllowGet);
        }
        #endregion


        #region 马上结算
        /// <summary>
        /// 马上结算
        /// </summary>
        /// <returns></returns>
        public ActionResult GotoBalance()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GotoBalance(GetPageMemCardsViewModel getMember)
        {
            var user = User as MyFormsPrincipal<loginUserDataDtoModel>;
            var id = user.UserData.U_ID;
            var result = consume.GotoBalance(getMember,id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region 会员减积分（马上扣除）
        public ActionResult DeductMemberPoint()
        {
            return View();
        }

        /// <summary>
        /// 马上扣除【操作ConsumeOrders表】
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeductMemberPoint(GetPageMemCardsViewModel getConsumeOrders)
        {
            try
            {
                var user = User as MyFormsPrincipal<loginUserDataDtoModel>;
                var id = user.UserData.U_ID;

                var result = consume.DeductMemberPoint(getConsumeOrders,id);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                throw ex;
            }
          
          
        }


        #endregion

        #region 马上返现
        public ActionResult GoTORecash()
        {
            return View();
        }
        /// <summary>
        /// 马上返现【操作ConsumeOrders表】
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GoTORecash(GetPageMemCardsViewModel getMemCards)
        {
            try
            {
                var result = consume.GoTORecash(getMemCards);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                throw ex;
            }


        }

        #endregion
        
        protected CardLevelsService level = new CardLevelsService();

        #region 积分返现统计 快速消费统计 获取消费记录中的信息
        /// <summary>
        /// 积分返现统计 快速消费统计 获取消费记录中的信息
        /// </summary>
        /// <returns></returns>
        public ActionResult ConsumeOrderInfo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ConsumeOrderInfo(GetPageConsumeOrdersViewModel getpage)
        {

            var result = consume.GetConsumeOrderList(getpage);
            return Json(result.data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 减积分统计  获取消费记录中的信息
        /// <summary>
        ///减积分统计  获取消费记录中的信息
        /// </summary>
        /// <returns></returns>
        public ActionResult ShowConsumeOrderInfo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ShowConsumeOrderInfo(GetPageConsumeOrdersViewModel getpage)
        {

            var result = consume.GetConsumeOrderList(getpage);
            return Json(result.data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 会员等级下拉框的绑定
        [HttpPost]
        public ActionResult BandcardLevels()
        {
            var result = level.GetCardLevels();
            return Json(result.data);
        }
        #endregion


    }
}

MemberPoint.Web/MemberPoint.Web/Controllers/MemCardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MemberPoint.Business;
using MemberPoint.Common;
using MemberPoint.Entity.POCOModel;
using MemberPoint.Entity.ViewModel;
using MemberPoint.Entity.DTOModel;
using System.Data;

namespace MemberPoint.Web.Controllers
{
    public class MemCardsController : Controller
    {

        private  MemCardsService member = new MemCardsService();
        private ExchangeGiftsService exchange = new ExchangeGiftsService();
        // GET: MemCards

        #region 查找会员
        public ActionResult FindMenberCard()
        {
            return View();
        }
        /// <summary>
        /// 查找会员
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult FindMenberCard(GetPageMemCardsViewModel getMember)
        {
            var list = member.FindMemCards(getMember);
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 积分兑换礼品
        //操作礼品表(ExchangGifts)
        public ActionResult PointChangeGifts()
        {
            return View();

        }
        [HttpPost]
        public ActionResult PointChangeGifts(GetPageMemCardsViewModel getMember)
        {
            var list = exchange.PointChangeGifts(getMember);
            return Json(list.data, JsonRequestBehavior.AllowGet);
        }

        #endregion


        private MemCardsService memcards = new MemCardsService();
        #region 会员展示
        /// <summary>
        /// 展示会员信息
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 获取用户数据
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult GetMemCardsList(GetPageViewModel model)
        {
            OpearteResult result;
            //获取当前用户所在店铺
            BaseService<MemberPoint.Entity.POCOModel.Users> UserBase = new BaseService<Entity.POCOModel.Users>();
            var user = User as MyFormsPrincipal<loginUserDataDtoModel>;
            result = memcards.GetMemCardsList(model, UserBase.Find(u => u.U_ID == user.UserData.U_ID).S_ID);
            return Json(result.data, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region 添加会员信息
        /// <summary>
        /// 添加会员
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            MemCardsViewModel m = new MemCardsViewModel();
            return View(m);
        }
        [HttpPost]
        public ActionResult Create(MemCardsViewModel modelinfo)
        {
            try
            {
                OpearteResult reselt;
                reselt = memcards.AddInfo(modelinfo);

                return Json(reselt);
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
        /// <summary>
        /// 查询姓名是否存在
        /// </summary>
        /// <param name="mName"></param>
        /// <returns></returns>
        public ActionResult selName(string mName)
        {
            OpearteResult result;
            if (memcards.Find(m => m.MC_Name == mName) != null)
            {
                result = new OpearteResult(ResultStatus.Success, "推荐人存在");
            }
            else
            {
                result = new OpearteResult(ResultStatus.Error, "推荐人不存在");
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        #endregion


        #region 修改会员信息
        /// <summary>
        /// 修改会员信息
        /// </summary>
        /// <returns></returns>
        public ActionResult Edit(string id)
        {

            try
            {
                OpearteResult result = memcards.Getfirst(id);

                return View("Create", result.data);
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }
        [HttpPost]
        public ActionResult Edit(MemCardsViewModel model)
        {
            try
            {
                OpearteResult reselt;
                reselt = memcards.UpdateMemCards(model);
                return Json(reselt);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        #endregion

        #region 删除会员信息
        /// <summary>
        /// 删除
        /// </summary>
        /// <returns></returns>
        public ActionResult Delete(string id)
        {
            OpearteResult result = memcards.DeleteMemCards(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 挂失锁定
        /// <summary>
        /// 挂失/锁定
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Lock(string id)
        {
            MemCardsViewModel m = new MemCardsViewModel()
            {
                MC_CardID = id
            };
            return View(m);
        }
        [HttpPost]
        public ActionResult Lock(MemCardsViewModel model)
        {
            try
            {
                OpearteResult result = memcards.LockMemCards(model);
                return Json(result);
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
        #endregion

        #region 会员转账
        public ActionResult VIPTransfer(string id)
        {
            var mem = memcards.Getfirst(id).data as MemCardsViewModel;
            TransferViewModel transfer = new TransferViewModel
            {
                Out_MC_CardID = mem.MC_CardID,
                Out_MC_Name = mem.MC_Name,
                Out_MC_Point = mem.MC_Point,
                Out_MC_TotalMoney = mem.MC_TotalMoney,
                MC_Money = mem.MC_Money
            };
            return View(transfer);
        }
        /// <summary>
        /// 执行转账
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult VIPTransfer(TransferViewModel model)
        {
            OpearteResult result;
            if (ModelState.IsValid)
            {
                var users = User as MyFormsPrincipal<loginUserDataDtoModel>;
                model.UserId = users.UserData.U_ID;
                result = memcards.VipTransfer(model);

            }
            else
            {
                result = new OpearteResult(ResultStatus.Error, "不能为空");
            }
            return Json(result);
        }

        /// <summary>
        /// 根据当前用户输入的卡号查询
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult VIPInto(string id)
        {
            OpearteResult result = memcards.Getfirst(id);
            return Json(result, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region 会员换卡
        /// <summary>
        /// VIP换卡
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult VIPReset(string id)
        {
            OpearteResult result = memcards.ResetGetBycard(id);
            return View(result.data);
        }


        /// <summary>
        /// 换卡事件
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult VIPReset(MemCardsViewModel model)
        {
            OpearteResult result = memcards.UpdateCards(model);
            return Json(result);
        }
        #endregion

        #region 导出Excel

        /// <summary>
        /// 导出Excel
        /// </summary>
        /// <returns></returns>
        public ActionResult ExportExcelNew()
        {
            string json = Request.Params["data"];
            try
            {
                DataTable dt = ExcelHelper.JsonToDataTable(json);
                string pathDestop = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
                ExcelHelper.GridToExcelByNPOI(dt, pathDestop + "\\" + "会员列表-" + DateTime.Now.ToString("yyyy-MM-dd") + "导出" + ".xls");
                return Content("1");
            }
            catch (Exception)
            {
                return Content("-1");
            }
        }
        #endregion


    }
}

MemberPoint.Web/MemberPoint.Web/Views/MemCards/Create.cshtml
@model MemberPoint.Entity.ViewModel.MemCardsViewModel

@{
    ViewBag.Title = "Create";
}

<script src="~/Scripts/validate.js"></script>
<script type="text/javascript">
    $(function () {
        $("#btnsubmit").click(function () {
            //if ($("#mName").val() != "")
            //    {
            var memid = $("#MC_ID").val();
            var pathurl;
            if(memid!=null &&  parseInt(memid)>0)
            {
                pathurl = "@Url.Action("Edit", "MemCards")";
            }
            else
            {
                pathurl="@Url.Action("Create", "MemCards")"
            }
            $("#Memform").form("submit", {
                url: pathurl,
                onSubmit: function () {
                    var isvalidata = $(this).form("enableValidation").form("validate");
                    return isvalidata;
                },
                success: function (data) {
                    var json = JSON.parse(data);
                    if (json.resultstatus == 1) {
                        window.parent.$.messager.alert("操作提示", json.Msg, "info")
                        window.parent.$("#win").window("close");
                        window.parent.$("#dg").datagrid("reload")
                    }
                    else {
                        window.parent.$.messager.alert("操作提示", json.Msg, "error")
                    }
                }
            })
            //}
            //else
            //{
            //    $.messager.alert("温馨提示","推荐人不能为空", "error");
            //}
            })

        //查询推荐人是否存在
        $("#btnsel").click(function () {
            $.getJSON("@Url.Action("selName", "MemCards")", { mName: $("#mName").val() }, function (data)
            {
                if (data.resultstatus == 1) {
                    $.messager.alert("操作提示", data.Msg, "info");
                }
                else {
                    $.messager.alert("温馨提示", data.Msg, "error");
                }
            })
        })


        $("#mName").keyup(function () {
            $("input[name=MC_RefererName]").val($("#mName").val())
            $("#_easyui_textbox_input5").val($("#mName").val())
        })
    })



</script>

@using (Html.BeginForm("", "", FormMethod.Post, new { id = "Memform", name = "Memform" }))
{
    <fieldset>
        <legend>会员基本信息</legend>
        <table>

            <tr>
                <td>
                    会员姓名：
                    @Html.EditorFor(model => model.MC_Name, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true" } })
                </td>
                <td></td>
                <td>
                    手机号码：
                    @Html.EditorFor(model => model.MC_Mobile, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true", validType = "mobile(MC_Mobile)" } })
                </td>
            </tr>

            <tr>
                <td>
                    卡片密码：
                    @Html.PasswordFor(model => model.MC_Password, new { @class = "easyui-textbox", data_options = "required:true" })
                </td>
                <td></td>
                <td>
                    确认密码：
                    @Html.PasswordFor(model => model.PasswordConfirm, new { @class = "easyui-textbox", data_options = "required:true", validType = "same['MC_Password']" })
                </td>
            </tr>

            <tr>
                <td>
                    会员性别：

                    <select id="MC_Sex" name="MC_Sex" class="easyui-combobox" data_options="required:true" style="width: 60px">
                        <option value="1">男</option>
                        <option value="2">女</option>
                    </select>
                </td>
                <td></td>
                <td>
                    会员等级：

                    <select id="CL_ID" name="CL_ID" class="easyui-combobox" data_options="required:true">
                        <option value="1">普通会员</option>
                        <option value="2">银卡会员</option>
                        <option value="3">金卡会员</option>
                        <option value="4">至尊VIP</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    会员生日：
                    @Html.CheckBoxFor(model => model.MC_BirthdayType, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true" } })公历
                <td></td>
                <td>
                    @Html.EditorFor(model => model.MC_Birthday_Month, new { htmlAttributes = new { @class = "easyui-numberbox", data_options = "required:true,min:1,max:12", style = "width: 50px" } })
                    月
                    @Html.EditorFor(model => model.MC_Birthday_Day, new { htmlAttributes = new { @class = "easyui-numberbox", data_options = "required:true,min:1,max:31", style = "width: 50px" } })
                    日
                </td>
            </tr>
            <tr>
                <td>@Html.CheckBoxFor(model => model.MC_IsPast, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true" } })设置卡片过期时间(到期则此卡自动失效)</td>
                <td></td>
                <td>@Html.EditorFor(model => model.MC_PastTime, new { htmlAttributes = new { @class = "easyui-datebox", data_options = "required:true" } })</td>
            </tr>
            <tr>
                <td>
                    卡片状态:<select id="MC_State" name="MC_State" class="easyui-combobox" data_options="required:true">
                        <option value="1">正常</option>
                    </select>
                </td>
                <td></td>
                <td>
                    卡片付费：
                    @Html.EditorFor(model => model.MC_Money, new { htmlAttributes = new { @class = "easyui-numberbox", data_options = "required:true,min:0" } })
                </td>
            </tr>
        </table>
        <hr />
        <table>
            <tr>
                <td>积分数量：</td>
                <td>@Html.EditorFor(model => model.MC_Point, new { htmlAttributes = new { @class = "easyui-numberbox", data_options = "required:true,min:0" } })</td>
                <td>
                    @Html.CheckBoxFor(model => model.MC_IsPointAuto, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true" } })
                    积分是否可以自动转换成等级
                </td>
            </tr>
            <tr>
                <td>推荐人：</td>
                <td>
                    @*@Html.EditorFor(model => model.MC_RefererCard, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true" } })*@
                    <input type="text" id="mName" autocomplete="off" name="mName" @*onkeydown="setTimeout('document.Memform.mName.value=document.Memform.MC_RefererName.value', 0)"*@ />
                    <a id="btnsel" href="javascript:void(0)" class="easyui-linkbutton">查找</a>
                </td>

                <td>
                    推荐人名称：

                    @Html.EditorFor(model => model.MC_RefererName, new { htmlAttributes = new { @class = "easyui-textbox", @readonly = "readonly" } })
                </td>
            </tr>
            <tr>
                <td>@Html.HiddenFor(model => model.MC_ID)</td>
                <td><a id="btnsubmit" href="javascript:void(0)" class="easyui-linkbutton">提交</a></td>
            </tr>
        </table>
    </fieldset>
}

MemberPoint.Web/MemberPoint.Web/Views/MemCards/FindMenberCard.cshtml
@{
    ViewBag.Title = "FindMenberCard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <title>快速消费</title>
    <script>
            $(function () {
                //查找会员
                $("#search").click(function () {
                    var cardid =$("#MC_CardID").val() 
                    $.post("@Url.Action("FindMenberCard", "MemCards")", { MC_CardID: cardid }, function (result) {
                        if (result.resultstatus == 1) {
                                  
                                     //如果成功则赋值
                                     $("#MC_CreateTime").text(result.data.MC_CreateTimeTo);
                                     $("#MC_Name").text(result.data.MC_Name);
                                     $("#MC_Point").text(result.data.MC_Point);
                                     $("#MC_TotalMoney").text(result.data.MC_TotalMoney);
                                     $("#CL_LevelName").text(result.data.CL_LevelName);
                                     $("#CL_Percent").text("(折扣比例：" + result.data.CL_Percent + ")");
                                     $("#CL_Percentto").text(result.data.CL_Percent);
                                     $("#CL_Point").text(result.data.CL_Point);
                                 }
                                 else {
                                     alert("无法找到此会员");
                                 }
                             }, "json");
                });
                //马上结算
                $("#balance").click(function () {
                    var card=$("#_easyui_textbox_input1").val();       
                    if (card == "" || card == null) {
                        $.messager.alert("提示信息", "请输入会员卡号，查询会员信息", "error");
                    }
                    else {
                    $.post("@Url.Action("GotoBalance", "ConsumeOrder")",
                       {
                           MC_CardID: $("#MC_CardID").val(),//会员卡号
                           CO_TotalMoney: $("#CO_TotalMoney").val(),//消费金额，额度
                           CL_Percent: $("#CL_Percentto").text(),
                           CL_Point: $("#CL_Point").text()

                       }, function (result)
                       {
                           if (result.resultstatus == 1) {
                               $.messager.alert("提示信息", "结算成功", "info");
                              
                               $("#MC_Point").text(result.data.MC_Point);
                               $("#MC_TotalMoney").text(result.data.MC_TotalMoney);
                               $("#_easyui_textbox_input3").val(result.data.CO_DiscountMoney);
                               $("#_easyui_textbox_input4").val(result.data.CL_PointTo);//累计积分数量
                           }
                           else {
                               $.messager.alert("提示信息", "结算失败", "info");
                               
                           }

                       }, "json");
                    }
                });
            });
            //radio的点击事件
            var flag = true;
            function chkRadio(id) {
                id.checked = flag;
                flag = !flag;
            }
    </script>
 
</head>
<body>
    <div style="padding:2px 5px;background:#fafafa;">
        <fieldset style="border:1px solid  #A4D1F0; height:120px; width:800px;font-size:14px;">
            <legend style="font-size:16px;">查找会员</legend>
            <table style="margin-top:20px;">
                <tr>
                    <td>卡号/手机：</td>
                    <td>
                        <input class="easyui-textbox" style="width:120px;" id="MC_CardID">
                    </td>
                    <td>
                        <a id="search" href="javascript:void(0)" class="easyui-linkbutton" style="width:40px">搜索</a>
                    </td>
                    <td>消费时间：</td>
                    <td><span id="MC_CreateTime"></span></td>
                </tr>
                <tr>
                    <td>姓名：</td>
                    <td>
                        <span id="MC_Name"></span>
                    </td>
                    <td></td>
                    <td>等级：</td>
                    <td><span id="CL_LevelName"></span><span id="CL_Percent"></span></td>
                </tr>
                <tr>
                    <td>当期积分：</td>
                    <td>
                        <span id="MC_Point" style="color:red"></span>
                    </td>
                    <td></td>
                    <td>累计消费：</td>
                    <td>
                        <span id="MC_TotalMoney"></span>
                    </td>
                </tr>
            </table>
        </fieldset>
        <fieldset style="border:1px solid  #A4D1F0; height:20px; width:800px;font-size:14px; color:red;">
            暂无优惠活动
        </fieldset>
        <table>
            <tr>
                <td>请输入消费金额：</td>
                <td><input class="easyui-textbox" id="CO_TotalMoney" style="width:120px; "></td>
                <td>此处输入金额按会员</td>
                <td>等级自动打折</td>
            </tr>
            <tr>
                <td>折后总金额：</td>
                <td><input class="easyui-textbox" readonly="true" id="CO_DiscountMoney"  style="width:120px; color:lightgray"></td>
                <td>可自动累计积分数量：</td>
                <td><input class="easyui-textbox"  readonly="true" id="CL_PointTo"  style="width:120px; color:lightgray "></td>
            </tr>
            <tr>
                <td>付款方式：</td>
                <td><input id="rType" type="radio" name="radio" onclick="chkRadio(this)" />现金支付</td>
                <td>优惠活动：<span style="color:red">暂无</span><span id="CL_Percentto" style="display:none"></span>
                    <span id="CL_Point" style="display:none;"></span>
                </td>
            </tr>
        </table>
        <br />
        <fieldset style="border:1px solid  #A4D1F0; height:150px; width:800px; font-size:14px;">
            <legend style="font-size:18px;">说明</legend>
            <p>输入实际的消费金额，系统将会自动按照会员等级中的设置暗战一定的比例计算积分并累计到会员账户</p>
            <p>在系统管理-->会员等级管理中可设置RMB和积分的兑换比例</p>
            <p>在系统管理-->会员等级管理中可设置是否允许直接输入折后总金额</p>
            <p>在系统管理-->会员等级管理中可设置是否允许直接输入累计积分数量</p>
        </fieldset>
        <br />
        <a href="javascript:void(0)" style="width:120px;" class="easyui-linkbutton" id="balance">马上结算</a>

    </div>
</body>
</html>

MemberPoint.Web/MemberPoint.Web/Views/MemCards/Lock.cshtml
@model MemberPoint.Entity.ViewModel.MemCardsViewModel

@{
    ViewBag.Title = "Lock";
}

<script type="text/javascript">
    @*$("#btnsubmit").click(function () {
        $.getJSON("@Url.Action("Lock", "MemCards")", { MC_State: $("#MC_State").val() }, function (data) {
            if (data.resultstatus == 1) {
                $.messager.alert("温馨提示", data.Msg, "info");
                window.parent.$("#win").window("close");
                window.parent.$("#dg").datagrid("reload")
            } else {
                $.messager.alert("温馨提示", data.Msg, "error");
            }
        })
    })*@

    $(function () {
        $("#btnsubmit").click(function () {
            $("#Memform").form("submit", {
                url: "@Url.Action("Lock", "MemCards")",
                onSubmit: function () {
                    var isvalidata = $(this).form("enableValidation").form("validate");
                    return isvalidata;
                },
            success: function (data) {
                var json = JSON.parse(data);
                if (json.resultstatus == 1) {
                    window.parent.$.messager.alert("操作提示", json.Msg, "info")
                    window.parent.$("#win").window("close");
                    window.parent.$("#dg").datagrid("reload")
                }
                else {
                    window.parent.$.messager.alert("操作提示", json.Msg, "error")
                }
            }
        })
        })
    })



</script>
@using (Html.BeginForm("", "", FormMethod.Post, new { id = "Memform" }))
{
    <fieldset>
        <legend>挂失/锁定</legend>
        <table>
            <tr>

                <td>会员卡号：</td>
                <td>@Html.EditorFor(model => model.MC_CardID, new { htmlAttributes = new { @class = "easyui-textbox", data_options = "required:true", @readonly = "readonly" } })</td>
            </tr>
            <tr>
                <td>状态：</td>
                <td>
                    卡片状态:<select id="MC_State" name="MC_State" class="easyui-combobox" data_options="required:true">
                        <option value="1">正常</option>
                        <option value="2">挂失</option>
                        <option value="3">锁定</option>
                    </select>
                </td>
            </tr>
            <tr><td><a id="btnsubmit" href="javascript:void(0)" class="easyui-linkbutton">提交</a></td></tr>
        </table>
    </fieldset>

}